# Generated by Django 4.2.3 on 2023-08-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='auction',
            field=models.BooleanField(help_text='Отметьте, если торг уместен', verbose_name='Торг'),
        ),
        migrations.AlterModelTable(
            name='advertisements',
            table='advertisements',
        ),
    ]
